/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "Vazir", "Tahoma", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        persian: ["Vazir", "Tahoma", "sans-serif"],
      },
      colors: {
        ocean: {
          50: "#f0f9ff",
          100: "#e0f2fe",
          200: "#bae6fd",
          300: "#7dd3fc",
          400: "#38bdf8",
          500: "#0ea5e9",
          600: "#0284c7",
          700: "#0369a1",
          800: "#075985",
          900: "#0c4a6e",
          950: "#082f49",
        },
        burgundy: {
          50: "#fff1f2",
          100: "#ffe4e6",
          200: "#fecdd3",
          300: "#fda4af",
          400: "#fb7185",
          500: "#f43f5e",
          600: "#e11d48",
          700: "#be123c",
          800: "#9f1239",
          900: "#881337",
          950: "#4c0519",
        },
        // Semantic color mappings
        primary: {
          50: "var(--color-primary-50)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
          950: "var(--color-primary-950)",
        },
        secondary: {
          50: "var(--color-secondary-50)",
          100: "var(--color-secondary-100)",
          200: "var(--color-secondary-200)",
          300: "var(--color-secondary-300)",
          400: "var(--color-secondary-400)",
          500: "var(--color-secondary-500)",
          600: "var(--color-secondary-600)",
          700: "var(--color-secondary-700)",
          800: "var(--color-secondary-800)",
          900: "var(--color-secondary-900)",
          950: "var(--color-secondary-950)",
        },
        error: {
          50: "var(--color-error-50)",
          100: "var(--color-error-100)",
          200: "var(--color-error-200)",
          300: "var(--color-error-300)",
          400: "var(--color-error-400)",
          500: "var(--color-error-500)",
          600: "var(--color-error-600)",
          700: "var(--color-error-700)",
          800: "var(--color-error-800)",
          900: "var(--color-error-900)",
          950: "var(--color-error-950)",
        },
        success: {
          50: "var(--color-success-50)",
          100: "var(--color-success-100)",
          200: "var(--color-success-200)",
          300: "var(--color-success-300)",
          400: "var(--color-success-400)",
          500: "var(--color-success-500)",
          600: "var(--color-success-600)",
          700: "var(--color-success-700)",
          800: "var(--color-success-800)",
          900: "var(--color-success-900)",
          950: "var(--color-success-950)",
        },
        warning: {
          50: "var(--color-warning-50)",
          100: "var(--color-warning-100)",
          200: "var(--color-warning-200)",
          300: "var(--color-warning-300)",
          400: "var(--color-warning-400)",
          500: "var(--color-warning-500)",
          600: "var(--color-warning-600)",
          700: "var(--color-warning-700)",
          800: "var(--color-warning-800)",
          900: "var(--color-warning-900)",
          950: "var(--color-warning-950)",
        },
      },
      fontSize: {
        "token-xs": "var(--font-size-xs)",
        "token-sm": "var(--font-size-sm)",
        "token-base": "var(--font-size-base)",
        "token-lg": "var(--font-size-lg)",
        "token-xl": "var(--font-size-xl)",
        "token-2xl": "var(--font-size-2xl)",
        "token-3xl": "var(--font-size-3xl)",
        "token-4xl": "var(--font-size-4xl)",
        "token-5xl": "var(--font-size-5xl)",
        "token-6xl": "var(--font-size-6xl)",
      },
      lineHeight: {
        "token-tight": "var(--line-height-tight)",
        "token-snug": "var(--line-height-snug)",
        "token-normal": "var(--line-height-normal)",
        "token-relaxed": "var(--line-height-relaxed)",
        "token-loose": "var(--line-height-loose)",
      },
      fontWeight: {
        "token-light": "var(--font-weight-light)",
        "token-normal": "var(--font-weight-normal)",
        "token-medium": "var(--font-weight-medium)",
        "token-semibold": "var(--font-weight-semibold)",
        "token-bold": "var(--font-weight-bold)",
        "token-extrabold": "var(--font-weight-extrabold)",
        "token-black": "var(--font-weight-black)",
      },
      letterSpacing: {
        "token-tighter": "var(--letter-spacing-tighter)",
        "token-tight": "var(--letter-spacing-tight)",
        "token-normal": "var(--letter-spacing-normal)",
        "token-wide": "var(--letter-spacing-wide)",
        "token-wider": "var(--letter-spacing-wider)",
        "token-widest": "var(--letter-spacing-widest)",
      },
      animation: {
        "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in": "fadeIn 0.2s ease-out",
        "slide-in": "slideIn 0.3s ease-out",
        "bounce-subtle": "bounceSubtle 2s infinite",
        shimmer: "shimmer 3s ease-in-out infinite",
        ripple: "ripple 0.6s ease-out",
        orbit: "orbit 6s linear infinite",
      },
      keyframes: {
        fadeIn: { "0%": { opacity: 0 }, "100%": { opacity: 1 } },
        slideIn: {
          "0%": { transform: "translateY(10px)", opacity: 0 },
          "100%": { transform: "translateY(0)", opacity: 1 },
        },
        bounceSubtle: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-3px)" },
        },
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        ripple: {
          "0%": { transform: "scale(0)", opacity: "1" },
          "100%": { transform: "scale(2)", opacity: "0" },
        },
        orbit: {
          "0%": { transform: "rotate(0deg) translateX(8px) rotate(0deg)" },
          "100%": {
            transform: "rotate(360deg) translateX(8px) rotate(-360deg)",
          },
        },
      },
      boxShadow: {
        soft: "0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
        depth:
          "0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)",
        "inner-light": "inset 0 2px 4px 0 rgba(0, 0, 0, 0.02)",
      },
      spacing: {
        "token-xs": "var(--spacing-xs)",
        "token-sm": "var(--spacing-sm)",
        "token-md": "var(--spacing-md)",
        "token-lg": "var(--spacing-lg)",
        "token-xl": "var(--spacing-xl)",
        "token-2xl": "var(--spacing-2xl)",
        "token-3xl": "var(--spacing-3xl)",
        "token-4xl": "var(--spacing-4xl)",
        "token-5xl": "var(--spacing-5xl)",
        panel: "var(--panel-padding)",
        "panel-gap": "var(--panel-gap)",
        "button-x": "var(--button-padding-x)",
        "button-y": "var(--button-padding-y)",
        "input-x": "var(--input-padding-x)",
        "input-y": "var(--input-padding-y)",
        modal: "var(--modal-padding)",
        "modal-gap": "var(--modal-gap)",
      },
      borderRadius: {
        "token-sm": "var(--radius-sm)",
        "token-md": "var(--radius-md)",
        "token-lg": "var(--radius-lg)",
        "token-xl": "var(--radius-xl)",
        "token-2xl": "var(--radius-2xl)",
        "token-3xl": "var(--radius-3xl)",
        "token-full": "var(--radius-full)",
      },
      boxShadow: {
        "token-sm": "var(--shadow-sm)",
        "token-md": "var(--shadow-md)",
        "token-lg": "var(--shadow-lg)",
        "token-xl": "var(--shadow-xl)",
        "token-2xl": "var(--shadow-2xl)",
        "token-inner": "var(--shadow-inner)",
        soft: "0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
        depth:
          "0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)",
        "inner-light": "inset 0 2px 4px 0 rgba(0, 0, 0, 0.02)",
      },
    },
  },
  plugins: [],
};
