#!/usr/bin/env python3
"""
Modern Interactive Dashboard Generator
Produces a self-contained HTML dashboard with visualizations
"""

import json
import base64
from pathlib import Path
from typing import Dict, Any, List
import textwrap


def generate_dashboard(report: Dict[str, Any], output_path: str = "optimization_dashboard.html"):
    """Generate complete interactive dashboard"""
    
    # Generate the HTML with embedded CSS and JavaScript
    html_content = generate_html_content(report)
    
    # Write to file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f"✅ Dashboard generated: {output_path}")
    return output_path


def generate_html_content(report: Dict[str, Any]) -> str:
    """Generate complete HTML with embedded CSS and JS"""
    
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project Optimization Dashboard</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        {get_css_styles()}
    </style>
</head>
<body>
    <div class="dashboard">
        <!-- Header -->
        <header class="dashboard-header">
            <div class="header-content">
                <h1><i class="fas fa-chart-network"></i> Project Architecture Analyzer</h1>
                <div class="header-subtitle">
                    <span class="project-path">{report['project_metadata']['root']}</span>
                    <span class="analysis-date">{report['project_metadata']['analysis_date']}</span>
                </div>
            </div>
            <div class="risk-badge risk-{report['risk_assessment']['overall_risk'].lower()}">
                {report['risk_assessment']['overall_risk']} RISK
            </div>
        </header>
        
        <!-- Summary Cards -->
        <section class="summary-section">
            <h2><i class="fas fa-tachometer-alt"></i> Executive Summary</h2>
            <div class="summary-cards">
                {generate_summary_cards(report)}
            </div>
        </section>
        
        <!-- Main Content -->
        <main class="dashboard-main">
            <div class="dashboard-grid">
                <!-- Left Column -->
                <div class="dashboard-column">
                    {generate_risk_assessment(report['risk_assessment'])}
                    {generate_unused_files(report['unused_files'])}
                    {generate_duplicate_files(report['duplicate_files'])}
                </div>
                
                <!-- Right Column -->
                <div class="dashboard-column">
                    {generate_merge_recommendations(report['merge_recommendations'])}
                    {generate_architecture_issues(report['architecture_issues'])}
                    {generate_refactor_plan(report['refactor_plan'])}
                </div>
            </div>
            
            <!-- Charts Section -->
            <section class="charts-section">
                <h2><i class="fas fa-chart-bar"></i> Analytics & Metrics</h2>
                <div class="charts-grid">
                    {generate_complexity_chart(report['statistics']['complexity_analysis'])}
                    {generate_file_type_chart(report['statistics']['file_type_distribution'])}
                    {generate_dependency_chart(report['statistics']['dependency_analysis'])}
                </div>
            </section>
        </main>
        
        <!-- Footer -->
        <footer class="dashboard-footer">
            <div class="footer-content">
                <div class="footer-actions">
                    <button class="btn btn-primary" onclick="exportReport()">
                        <i class="fas fa-download"></i> Export Report
                    </button>
                    <button class="btn btn-secondary" onclick="printDashboard()">
                        <i class="fas fa-print"></i> Print
                    </button>
                </div>
                <div class="footer-info">
                    <p>Generated by Advanced Architecture Analyzer • Safe refactoring recommendations only</p>
                    <p class="disclaimer">⚠️ Always test changes in a controlled environment before production</p>
                </div>
            </div>
        </footer>
    </div>
    
    <!-- Export Modal -->
    <div id="exportModal" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeModal()">&times;</span>
            <h3>Export Report</h3>
            <div class="export-options">
                <button class="btn" onclick="exportJSON()">
                    <i class="fas fa-file-code"></i> JSON Data
                </button>
                <button class="btn" onclick="exportCSV()">
                    <i class="fas fa-file-csv"></i> CSV Summary
                </button>
                <button class="btn" onclick="exportMarkdown()">
                    <i class="fas fa-file-alt"></i> Markdown Report
                </button>
            </div>
        </div>
    </div>
    
    <script>
        {get_javascript_code(report)}
    </script>
</body>
</html>"""


def get_css_styles() -> str:
    """Return embedded CSS styles"""
    return """
    :root {
        --primary-color: #6366f1;
        --secondary-color: #8b5cf6;
        --success-color: #10b981;
        --warning-color: #f59e0b;
        --danger-color: #ef4444;
        --info-color: #3b82f6;
        --dark-bg: #0f172a;
        --dark-card: #1e293b;
        --dark-border: #334155;
        --dark-hover: #2d3748;
        --text-primary: #f1f5f9;
        --text-secondary: #94a3b8;
        --text-muted: #64748b;
        --radius-lg: 12px;
        --radius-md: 8px;
        --radius-sm: 4px;
        --shadow-lg: 0 10px 25px -5px rgba(0, 0, 0, 0.5);
        --shadow-md: 0 4px 6px -1px rgba(0, 0, 0, 0.3);
        --shadow-sm: 0 1px 3px 0 rgba(0, 0, 0, 0.2);
        --transition: all 0.2s ease;
    }
    
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    
    body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Inter', Roboto, sans-serif;
        background: linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%);
        color: var(--text-primary);
        line-height: 1.6;
        min-height: 100vh;
    }
    
    .dashboard {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        max-width: 1600px;
        margin: 0 auto;
        padding: 20px;
    }
    
    /* Header */
    .dashboard-header {
        background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
        border-radius: var(--radius-lg);
        padding: 25px 30px;
        margin-bottom: 30px;
        display: flex;
        justify-content: space-between;
        align-items: center;
        box-shadow: var(--shadow-lg);
        animation: slideDown 0.5s ease;
    }
    
    @keyframes slideDown {
        from { opacity: 0; transform: translateY(-20px); }
        to { opacity: 1; transform: translateY(0); }
    }
    
    .header-content h1 {
        font-size: 28px;
        font-weight: 700;
        margin-bottom: 5px;
        display: flex;
        align-items: center;
        gap: 12px;
    }
    
    .header-subtitle {
        display: flex;
        gap: 20px;
        color: rgba(255, 255, 255, 0.9);
        font-size: 14px;
    }
    
    .project-path {
        font-family: 'Monaco', 'Consolas', monospace;
        background: rgba(0, 0, 0, 0.2);
        padding: 4px 10px;
        border-radius: var(--radius-sm);
    }
    
    .risk-badge {
        padding: 10px 20px;
        border-radius: 50px;
        font-weight: 700;
        font-size: 14px;
        letter-spacing: 1px;
        text-transform: uppercase;
        box-shadow: var(--shadow-md);
        transition: var(--transition);
    }
    
    .risk-badge:hover {
        transform: scale(1.05);
    }
    
    .risk-high {
        background: var(--danger-color);
        color: white;
    }
    
    .risk-medium {
        background: var(--warning-color);
        color: #000;
    }
    
    .risk-low {
        background: var(--success-color);
        color: white;
    }
    
    /* Summary Section */
    .summary-section {
        margin-bottom: 30px;
    }
    
    .summary-section h2 {
        font-size: 20px;
        margin-bottom: 15px;
        display: flex;
        align-items: center;
        gap: 10px;
        color: var(--text-primary);
    }
    
    .summary-cards {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
        gap: 20px;
    }
    
    .summary-card {
        background: var(--dark-card);
        border-radius: var(--radius-md);
        padding: 20px;
        border: 1px solid var(--dark-border);
        transition: var(--transition);
        position: relative;
        overflow: hidden;
    }
    
    .summary-card:hover {
        transform: translateY(-3px);
        box-shadow: var(--shadow-md);
        border-color: var(--primary-color);
    }
    
    .summary-card::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        height: 4px;
        background: linear-gradient(90deg, var(--primary-color), var(--secondary-color));
    }
    
    .card-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 15px;
    }
    
    .card-icon {
        font-size: 24px;
        color: var(--primary-color);
    }
    
    .card-value {
        font-size: 32px;
        font-weight: 700;
        margin-bottom: 5px;
        background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
    }
    
    .card-label {
        color: var(--text-secondary);
        font-size: 14px;
        text-transform: uppercase;
        letter-spacing: 1px;
    }
    
    .card-trend {
        font-size: 12px;
        padding: 4px 10px;
        border-radius: 20px;
        background: rgba(16, 185, 129, 0.2);
        color: var(--success-color);
    }
    
    /* Main Content */
    .dashboard-main {
        flex: 1;
    }
    
    .dashboard-grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 25px;
        margin-bottom: 30px;
    }
    
    @media (max-width: 1200px) {
        .dashboard-grid {
            grid-template-columns: 1fr;
        }
    }
    
    .dashboard-column {
        display: flex;
        flex-direction: column;
        gap: 25px;
    }
    
    /* Panel Styles */
    .panel {
        background: var(--dark-card);
        border-radius: var(--radius-md);
        border: 1px solid var(--dark-border);
        overflow: hidden;
        transition: var(--transition);
    }
    
    .panel:hover {
        box-shadow: var(--shadow-md);
    }
    
    .panel-header {
        padding: 18px 24px;
        background: rgba(0, 0, 0, 0.2);
        border-bottom: 1px solid var(--dark-border);
        display: flex;
        justify-content: space-between;
        align-items: center;
        cursor: pointer;
        transition: var(--transition);
    }
    
    .panel-header:hover {
        background: var(--dark-hover);
    }
    
    .panel-header h3 {
        font-size: 16px;
        font-weight: 600;
        display: flex;
        align-items: center;
        gap: 10px;
    }
    
    .panel-badge {
        padding: 4px 12px;
        border-radius: 20px;
        font-size: 12px;
        font-weight: 600;
        background: var(--dark-border);
    }
    
    .panel-content {
        padding: 0;
        max-height: 400px;
        overflow-y: auto;
        transition: max-height 0.3s ease;
    }
    
    .panel.collapsed .panel-content {
        max-height: 0;
        padding: 0;
    }
    
    /* List Items */
    .list-item {
        padding: 16px 24px;
        border-bottom: 1px solid var(--dark-border);
        display: flex;
        justify-content: space-between;
        align-items: center;
        transition: var(--transition);
    }
    
    .list-item:hover {
        background: var(--dark-hover);
    }
    
    .list-item:last-child {
        border-bottom: none;
    }
    
    .item-path {
        font-family: 'Monaco', 'Consolas', monospace;
        font-size: 13px;
        color: var(--text-primary);
        flex: 1;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
    
    .item-meta {
        display: flex;
        gap: 10px;
        align-items: center;
        font-size: 12px;
        color: var(--text-secondary);
    }
    
    .item-tag {
        padding: 3px 10px;
        border-radius: 12px;
        font-size: 11px;
        font-weight: 600;
        text-transform: uppercase;
    }
    
    .tag-success { background: rgba(16, 185, 129, 0.2); color: var(--success-color); }
    .tag-warning { background: rgba(245, 158, 11, 0.2); color: var(--warning-color); }
    .tag-danger { background: rgba(239, 68, 68, 0.2); color: var(--danger-color); }
    .tag-info { background: rgba(59, 130, 246, 0.2); color: var(--info-color); }
    
    /* Charts */
    .charts-section {
        margin-top: 30px;
    }
    
    .charts-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
        gap: 25px;
        margin-top: 20px;
    }
    
    .chart-container {
        background: var(--dark-card);
        border-radius: var(--radius-md);
        padding: 20px;
        border: 1px solid var(--dark-border);
    }
    
    .chart-header {
        margin-bottom: 15px;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    
    .chart-title {
        font-size: 16px;
        font-weight: 600;
        color: var(--text-primary);
    }
    
    .chart-canvas {
        width: 100%;
        height: 200px;
        position: relative;
    }
    
    /* Buttons */
    .btn {
        padding: 10px 20px;
        border-radius: var(--radius-md);
        border: none;
        font-weight: 600;
        font-size: 14px;
        cursor: pointer;
        transition: var(--transition);
        display: inline-flex;
        align-items: center;
        gap: 8px;
    }
    
    .btn:hover {
        transform: translateY(-2px);
        box-shadow: var(--shadow-md);
    }
    
    .btn-primary {
        background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
        color: white;
    }
    
    .btn-secondary {
        background: var(--dark-border);
        color: var(--text-primary);
    }
    
    /* Footer */
    .dashboard-footer {
        margin-top: 40px;
        padding-top: 20px;
        border-top: 1px solid var(--dark-border);
    }
    
    .footer-content {
        display: flex;
        justify-content: space-between;
        align-items: center;
        flex-wrap: wrap;
        gap: 20px;
    }
    
    .footer-actions {
        display: flex;
        gap: 10px;
    }
    
    .footer-info {
        text-align: right;
        color: var(--text-secondary);
        font-size: 13px;
    }
    
    .disclaimer {
        color: var(--warning-color);
        font-size: 12px;
        margin-top: 5px;
    }
    
    /* Modal */
    .modal {
        display: none;
        position: fixed;
        z-index: 1000;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        background: rgba(0, 0, 0, 0.8);
        justify-content: center;
        align-items: center;
    }
    
    .modal-content {
        background: var(--dark-card);
        border-radius: var(--radius-lg);
        padding: 30px;
        width: 90%;
        max-width: 500px;
        position: relative;
        box-shadow: var(--shadow-lg);
        animation: modalSlide 0.3s ease;
    }
    
    @keyframes modalSlide {
        from { opacity: 0; transform: translateY(-30px); }
        to { opacity: 1; transform: translateY(0); }
    }
    
    .close {
        position: absolute;
        top: 20px;
        right: 25px;
        font-size: 28px;
        cursor: pointer;
        color: var(--text-secondary);
    }
    
    .close:hover {
        color: var(--text-primary);
    }
    
    .export-options {
        display: flex;
        flex-direction: column;
        gap: 15px;
        margin-top: 20px;
    }
    
    /* Scrollbar */
    ::-webkit-scrollbar {
        width: 8px;
        height: 8px;
    }
    
    ::-webkit-scrollbar-track {
        background: var(--dark-border);
        border-radius: 4px;
    }
    
    ::-webkit-scrollbar-thumb {
        background: var(--primary-color);
        border-radius: 4px;
    }
    
    ::-webkit-scrollbar-thumb:hover {
        background: var(--secondary-color);
    }
    
    /* Responsive */
    @media (max-width: 768px) {
        .dashboard {
            padding: 15px;
        }
        
        .dashboard-header {
            flex-direction: column;
            gap: 15px;
            text-align: center;
        }
        
        .summary-cards {
            grid-template-columns: 1fr;
        }
        
        .charts-grid {
            grid-template-columns: 1fr;
        }
        
        .footer-content {
            flex-direction: column;
            text-align: center;
        }
    }
    """


def generate_summary_cards(report: Dict[str, Any]) -> str:
    """Generate summary cards HTML"""
    metadata = report['project_metadata']
    stats = report['statistics']['complexity_analysis']
    
    cards = [
        {
            'icon': 'fas fa-file-code',
            'value': metadata['total_files'],
            'label': 'Total Files',
            'trend': f"{len(report['languages'])} languages"
        },
        {
            'icon': 'fas fa-trash-alt',
            'value': len(report['unused_files']),
            'label': 'Unused Files',
            'trend': 'Safe to remove',
            'color': 'danger'
        },
        {
            'icon': 'fas fa-copy',
            'value': len(report['duplicate_files']),
            'label': 'Duplicate Groups',
            'trend': f"{sum(len(g['files']) for g in report['duplicate_files'])} files"
        },
        {
            'icon': 'fas fa-merge',
            'value': len(report['merge_recommendations']),
            'label': 'Merge Candidates',
            'trend': 'Optimization potential'
        },
        {
            'icon': 'fas fa-chart-line',
            'value': f"{stats['average_maintainability']}/100",
            'label': 'Avg Maintainability',
            'trend': 'Higher is better'
        },
        {
            'icon': 'fas fa-exclamation-triangle',
            'value': report['risk_assessment']['overall_risk'],
            'label': 'Risk Level',
            'trend': f"Score: {report['risk_assessment']['risk_score']}"
        }
    ]
    
    html_cards = []
    for card in cards:
        color_class = f"color-{card.get('color', 'primary')}"
        html_cards.append(f"""
        <div class="summary-card">
            <div class="card-header">
                <div class="card-icon {color_class}">
                    <i class="{card['icon']}"></i>
                </div>
                <span class="card-trend">{card['trend']}</span>
            </div>
            <div class="card-value">{card['value']}</div>
            <div class="card-label">{card['label']}</div>
        </div>
        """)
    
    return ''.join(html_cards)


def generate_risk_assessment(assessment: Dict[str, Any]) -> str:
    """Generate risk assessment panel"""
    items_html = []
    for factor, score in assessment['risk_factors'].items():
        items_html.append(f"""
        <div class="list-item">
            <div class="item-path">{factor.replace('_', ' ').title()}</div>
            <div class="item-meta">
                <span class="item-tag tag-warning">Score: {score}</span>
            </div>
        </div>
        """)
    
    for item in assessment.get('high_risk_items', []):
        items_html.append(f"""
        <div class="list-item">
            <div class="item-path">{item.get('hook', item.get('component', 'Unknown'))}</div>
            <div class="item-meta">
                <span class="item-tag tag-danger">High Risk</span>
                <span>{item.get('count', 1)} duplicates</span>
            </div>
        </div>
        """)
    
    return f"""
    <div class="panel">
        <div class="panel-header" onclick="togglePanel(this)">
            <h3><i class="fas fa-exclamation-circle"></i> Risk Assessment</h3>
            <span class="panel-badge risk-{assessment['overall_risk'].lower()}">
                {assessment['overall_risk']}
            </span>
        </div>
        <div class="panel-content">
            {"".join(items_html)}
            <div class="list-item">
                <div class="item-path">Mitigation Strategy</div>
                <div class="item-meta">
                    <span class="item-tag tag-info">See Refactor Plan</span>
                </div>
            </div>
        </div>
    </div>
    """


def generate_unused_files(unused_files: List[Dict]) -> str:
    """Generate unused files panel"""
    items_html = []
    for file in unused_files[:15]:  # Show first 15
        potential = file['potential_value']
        tag_class = 'tag-success' if potential['score'] < 50 else 'tag-warning'
        
        items_html.append(f"""
        <div class="list-item">
            <div class="item-path">{file['path']}</div>
            <div class="item-meta">
                <span class="item-tag {tag_class}">{potential['recommendation']}</span>
                <span>{file['lines']} lines</span>
                <span>{file['size']} bytes</span>
            </div>
        </div>
        """)
    
    if len(unused_files) > 15:
        items_html.append(f"""
        <div class="list-item">
            <div class="item-path">... and {len(unused_files) - 15} more files</div>
            <div class="item-meta">
                <span class="item-tag tag-info">View all in JSON</span>
            </div>
        </div>
        """)
    
    return f"""
    <div class="panel">
        <div class="panel-header" onclick="togglePanel(this)">
            <h3><i class="fas fa-trash-alt"></i> Unused Files</h3>
            <span class="panel-badge">{len(unused_files)} files</span>
        </div>
        <div class="panel-content">
            {"".join(items_html)}
        </div>
    </div>
    """


def generate_duplicate_files(duplicate_files: List[Dict]) -> str:
    """Generate duplicate files panel"""
    items_html = []
    for group in duplicate_files[:10]:  # Show first 10 groups
        files = group['files']
        savings = group['savings_potential']
        
        items_html.append(f"""
        <div class="list-item">
            <div class="item-path">{len(files)} identical files</div>
            <div class="item-meta">
                <span class="item-tag tag-warning">{savings} bytes savings</span>
                <span>Group: {group['group_id']}</span>
            </div>
        </div>
        """)
        
        # Show first file in group as example
        if files:
            items_html.append(f"""
            <div class="list-item" style="padding-left: 40px; background: rgba(0,0,0,0.1);">
                <div class="item-path">Example: {files[0]['path']}</div>
                <div class="item-meta">
                    <span>{files[0]['dependents']} imports</span>
                </div>
            </div>
            """)
    
    return f"""
    <div class="panel">
        <div class="panel-header" onclick="togglePanel(this)">
            <h3><i class="fas fa-copy"></i> Duplicate Files</h3>
            <span class="panel-badge">{len(duplicate_files)} groups</span>
        </div>
        <div class="panel-content">
            {"".join(items_html)}
        </div>
    </div>
    """


def generate_merge_recommendations(recommendations: List[Dict]) -> str:
    """Generate merge recommendations panel"""
    items_html = []
    for rec in recommendations[:10]:  # Show first 10
        risk_class = f"risk-{rec['risk_level'].lower()}"
        
        items_html.append(f"""
        <div class="list-item">
            <div class="item-path">{rec['common_name']}</div>
            <div class="item-meta">
                <span class="item-tag {risk_class}">{rec['risk_level']}</span>
                <span>{len(rec['files'])} files</span>
            </div>
        </div>
        
        <div class="list-item" style="padding-left: 40px; background: rgba(0,0,0,0.1);">
            <div class="item-path">Keep: {rec['best_candidate']}</div>
            <div class="item-meta">
                <span class="item-tag tag-success">Maintainability: {rec['best_maintainability']}</span>
            </div>
        </div>
        """)
    
    return f"""
    <div class="panel">
        <div class="panel-header" onclick="togglePanel(this)">
            <h3><i class="fas fa-merge"></i> Merge Recommendations</h3>
            <span class="panel-badge">{len(recommendations)} candidates</span>
        </div>
        <div class="panel-content">
            {"".join(items_html)}
        </div>
    </div>
    """


def generate_architecture_issues(issues: Dict[str, Any]) -> str:
    """Generate architecture issues panel"""
    items_html = []
    
    # Duplicate hooks
    for hook in issues.get('duplicate_hooks', [])[:5]:
        items_html.append(f"""
        <div class="list-item">
            <div class="item-path">{hook['hook']}</div>
            <div class="item-meta">
                <span class="item-tag tag-warning">{hook['count']} duplicates</span>
            </div>
        </div>
        """)
    
    # Unwired services
    for service in issues.get('unwired_services', [])[:5]:
        items_html.append(f"""
        <div class="list-item">
            <div class="item-path">{service['service']}</div>
            <div class="item-meta">
                <span class="item-tag tag-danger">Unused</span>
            </div>
        </div>
        """)
    
    # Multiple layouts
    if issues.get('multiple_layouts'):
        items_html.append(f"""
        <div class="list-item">
            <div class="item-path">Multiple Layout Files</div>
            <div class="item-meta">
                <span class="item-tag tag-warning">{len(issues['multiple_layouts'])} found</span>
            </div>
        </div>
        """)
    
    return f"""
    <div class="panel">
        <div class="panel-header" onclick="togglePanel(this)">
            <h3><i class="fas fa-exclamation-triangle"></i> Architecture Issues</h3>
            <span class="panel-badge">{
                len(issues.get('duplicate_hooks', [])) + 
                len(issues.get('unwired_services', []))
            } issues</span>
        </div>
        <div class="panel-content">
            {"".join(items_html)}
        </div>
    </div>
    """


def generate_refactor_plan(plan: List[Dict]) -> str:
    """Generate refactor plan panel"""
    items_html = []
    for phase in plan:
        risk_class = f"risk-{phase['risk'].lower().replace('-', '_').split('_')[0]}"
        
        items_html.append(f"""
        <div class="list-item">
            <div class="item-path">
                <strong>Phase {phase['phase']}: {phase['name']}</strong>
                <div style="font-size: 12px; color: var(--text-secondary); margin-top: 5px;">
                    Duration: {phase['duration']} • Risk: {phase['risk']}
                </div>
            </div>
            <div class="item-meta">
                <span class="item-tag {risk_class}">{phase['risk']}</span>
            </div>
        </div>
        
        <div class="list-item" style="padding-left: 40px; background: rgba(0,0,0,0.1); font-size: 13px;">
            <div class="item-path">
                {phase['tasks'][0] if phase['tasks'] else 'No tasks defined'}
            </div>
        </div>
        """)
    
    return f"""
    <div class="panel">
        <div class="panel-header" onclick="togglePanel(this)">
            <h3><i class="fas fa-road"></i> Refactoring Roadmap</h3>
            <span class="panel-badge">{len(plan)} phases</span>
        </div>
        <div class="panel-content">
            {"".join(items_html)}
        </div>
    </div>
    """


def generate_complexity_chart(analysis: Dict[str, Any]) -> str:
    """Generate complexity chart"""
    return f"""
    <div class="chart-container">
        <div class="chart-header">
            <div class="chart-title">Complexity Analysis</div>
        </div>
        <div class="chart-canvas">
            <canvas id="complexityChart" width="400" height="200"></canvas>
        </div>
        <div style="margin-top: 15px; font-size: 12px; color: var(--text-secondary);">
            <div style="display: flex; justify-content: space-between;">
                <span>Avg Complexity: {analysis['average_complexity']}</span>
                <span>Complex Files: {analysis['complex_files']}</span>
            </div>
        </div>
    </div>
    """


def generate_file_type_chart(distribution: Dict[str, float]) -> str:
    """Generate file type distribution chart"""
    chart_data = []
    for lang, percentage in list(distribution.items())[:8]:  # Top 8
        chart_data.append(f"{{lang: '{lang}', percentage: {percentage}}}")
    
    return f"""
    <div class="chart-container">
        <div class="chart-header">
            <div class="chart-title">File Type Distribution</div>
        </div>
        <div class="chart-canvas">
            <canvas id="fileTypeChart" width="400" height="200"></canvas>
        </div>
        <div style="margin-top: 15px; font-size: 12px; color: var(--text-secondary);">
            Showing top {min(8, len(distribution))} of {len(distribution)} languages
        </div>
    </div>
    """


def generate_dependency_chart(analysis: Dict[str, Any]) -> str:
    """Generate dependency analysis chart"""
    return f"""
    <div class="chart-container">
        <div class="chart-header">
            <div class="chart-title">Dependency Analysis</div>
        </div>
        <div class="chart-canvas">
            <canvas id="dependencyChart" width="400" height="200"></canvas>
        </div>
        <div style="margin-top: 15px; font-size: 12px; color: var(--text-secondary);">
            <div style="display: flex; justify-content: space-between;">
                <span>Orphaned Files: {analysis['orphaned_files']}</span>
                <span>Highly Connected: {analysis['highly_connected']}</span>
            </div>
        </div>
    </div>
    """


def get_javascript_code(report: Dict[str, Any]) -> str:
    """Return embedded JavaScript code"""
    return f"""
    // Panel toggle functionality
    function togglePanel(header) {{
        const panel = header.parentElement;
        panel.classList.toggle('collapsed');
        
        const icon = header.querySelector('i');
        if (panel.classList.contains('collapsed')) {{
            icon.style.transform = 'rotate(-90deg)';
        }} else {{
            icon.style.transform = 'rotate(0deg)';
        }}
    }}
    
    // Initialize all panels as expanded
    document.addEventListener('DOMContentLoaded', function() {{
        // Draw charts
        drawComplexityChart({json.dumps(report['statistics']['complexity_analysis'])});
        drawFileTypeChart({json.dumps(report['statistics']['file_type_distribution'])});
        drawDependencyChart({json.dumps(report['statistics']['dependency_analysis'])});
        
        // Add click handlers to all panel headers
        document.querySelectorAll('.panel-header').forEach(header => {{
            header.addEventListener('click', () => togglePanel(header));
        }});
    }});
    
    // Chart drawing functions
    function drawComplexityChart(data) {{
        const canvas = document.getElementById('complexityChart');
        if (!canvas) return;
        
        const ctx = canvas.getContext('2d');
        const width = canvas.width;
        const height = canvas.height;
        
        // Clear canvas
        ctx.clearRect(0, 0, width, height);
        
        // Draw bar for average complexity
        const avgComplexity = data.average_complexity || 0;
        const maxComplexity = data.max_complexity || 100;
        const barWidth = 60;
        const barHeight = (avgComplexity / maxComplexity) * (height - 40);
        const x = width / 2 - barWidth / 2;
        const y = height - 40 - barHeight;
        
        // Gradient fill
        const gradient = ctx.createLinearGradient(0, y, 0, height - 40);
        gradient.addColorStop(0, '#8b5cf6');
        gradient.addColorStop(1, '#6366f1');
        
        // Draw bar
        ctx.fillStyle = gradient;
        ctx.fillRect(x, y, barWidth, barHeight);
        
        // Draw label
        ctx.fillStyle = '#f1f5f9';
        ctx.font = '14px sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText('Avg Complexity', width / 2, height - 20);
        ctx.fillText(avgComplexity.toFixed(1), width / 2, y - 10);
        
        // Draw complexity scale
        ctx.fillStyle = '#64748b';
        ctx.font = '12px sans-serif';
        ctx.fillText('0', 10, height - 20);
        ctx.fillText(maxComplexity, 10, 30);
    }}
    
    function drawFileTypeChart(distribution) {{
        const canvas = document.getElementById('fileTypeChart');
        if (!canvas) return;
        
        const ctx = canvas.getContext('2d');
        const width = canvas.width;
        const height = canvas.height;
        
        // Clear canvas
        ctx.clearRect(0, 0, width, height);
        
        // Convert distribution to array and sort
        const items = Object.entries(distribution)
            .sort((a, b) => b[1] - a[1])
            .slice(0, 5); // Top 5
        
        if (items.length === 0) return;
        
        const barWidth = 40;
        const spacing = 20;
        const maxPercentage = Math.max(...items.map(i => i[1]));
        const totalWidth = items.length * (barWidth + spacing) - spacing;
        const startX = (width - totalWidth) / 2;
        
        // Colors for bars
        const colors = [
            'rgba(99, 102, 241, 0.8)',
            'rgba(139, 92, 246, 0.8)',
            'rgba(16, 185, 129, 0.8)',
            'rgba(245, 158, 11, 0.8)',
            'rgba(239, 68, 68, 0.8)'
        ];
        
        // Draw bars
        items.forEach(([lang, percentage], index) => {{
            const x = startX + index * (barWidth + spacing);
            const barHeight = (percentage / maxPercentage) * (height - 60);
            const y = height - 50 - barHeight;
            
            // Draw bar
            ctx.fillStyle = colors[index % colors.length];
            ctx.fillRect(x, y, barWidth, barHeight);
            
            // Draw label
            ctx.fillStyle = '#f1f5f9';
            ctx.font = '12px sans-serif';
            ctx.textAlign = 'center';
            ctx.fillText(lang.substring(0, 8), x + barWidth / 2, height - 30);
            ctx.fillText(percentage.toFixed(1) + '%', x + barWidth / 2, y - 10);
        }});
    }}
    
    function drawDependencyChart(data) {{
        const canvas = document.getElementById('dependencyChart');
        if (!canvas) return;
        
        const ctx = canvas.getContext('2d');
        const width = canvas.width;
        const height = canvas.height;
        
        // Clear canvas
        ctx.clearRect(0, 0, width, height);
        
        // Draw donut chart
        const centerX = width / 2;
        const centerY = height / 2;
        const radius = Math.min(centerX, centerY) - 20;
        
        const metrics = [
            {{ label: 'Orphaned', value: data.orphaned_files || 0, color: '#ef4444' }},
            {{ label: 'Normal', value: 100 - (data.orphaned_files || 0) - (data.highly_connected || 0), color: '#3b82f6' }},
            {{ label: 'Connected', value: data.highly_connected || 0, color: '#10b981' }}
        ].filter(m => m.value > 0);
        
        let startAngle = 0;
        
        metrics.forEach(metric => {{
            const sliceAngle = (metric.value / 100) * 2 * Math.PI;
            
            // Draw slice
            ctx.beginPath();
            ctx.moveTo(centerX, centerY);
            ctx.arc(centerX, centerY, radius, startAngle, startAngle + sliceAngle);
            ctx.closePath();
            ctx.fillStyle = metric.color;
            ctx.fill();
            
            startAngle += sliceAngle;
        }});
        
        // Draw center text
        ctx.fillStyle = '#f1f5f9';
        ctx.font = '16px sans-serif';
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';
        ctx.fillText('Dependencies', centerX, centerY);
        
        // Draw legend
        let legendY = 30;
        metrics.forEach(metric => {{
            ctx.fillStyle = metric.color;
            ctx.fillRect(20, legendY, 15, 15);
            
            ctx.fillStyle = '#94a3b8';
            ctx.font = '12px sans-serif';
            ctx.textAlign = 'left';
            ctx.fillText(`${{metric.label}}: ${{metric.value}}%`, 40, legendY + 12);
            
            legendY += 20;
        }});
    }}
    
    // Modal functionality
    function showModal() {{
        document.getElementById('exportModal').style.display = 'flex';
    }}
    
    function closeModal() {{
        document.getElementById('exportModal').style.display = 'none';
    }}
    
    // Export functionality
    function exportReport() {{
        showModal();
    }}
    
    function exportJSON() {{
        const dataStr = JSON.stringify({json.dumps(report, indent=2)}, null, 2);
        const dataUri = 'data:application/json;charset=utf-8,' + encodeURIComponent(dataStr);
        const link = document.createElement('a');
        link.setAttribute('href', dataUri);
        link.setAttribute('download', 'architecture_analysis_report.json');
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        closeModal();
    }}
    
    function exportCSV() {{
        // Create simple CSV summary
        let csv = 'Category,Count,Details\\n';
        csv += `Total Files,${{report['project_metadata']['total_files']}},\\n`;
        csv += `Unused Files,${{len(report['unused_files'])}},\\n`;
        csv += `Duplicate Groups,${{len(report['duplicate_files'])}},\\n`;
        csv += `Merge Candidates,${{len(report['merge_recommendations'])}},\\n`;
        csv += `Risk Level,${{report['risk_assessment']['overall_risk']}},\\n`;
        
        const dataUri = 'data:text/csv;charset=utf-8,' + encodeURIComponent(csv);
        const link = document.createElement('a');
        link.setAttribute('href', dataUri);
        link.setAttribute('download', 'analysis_summary.csv');
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        closeModal();
    }}
    
    function exportMarkdown() {{
        // Create markdown report
        let md = '# Architecture Analysis Report\\n\\n';
        md += `**Project:** ${{report['project_metadata']['root']}}\\n`;
        md += `**Analysis Date:** ${{report['project_metadata']['analysis_date']}}\\n\\n`;
        
        md += '## Summary\\n\\n';
        md += `- **Total Files:** ${{report['project_metadata']['total_files']}}\\n`;
        md += `- **Unused Files:** ${{len(report['unused_files'])}}\\n`;
        md += `- **Duplicate Groups:** ${{len(report['duplicate_files'])}}\\n`;
        md += `- **Risk Level:** ${{report['risk_assessment']['overall_risk']}}\\n\\n`;
        
        md += '## Top Recommendations\\n\\n';
        
        if (report['merge_recommendations'].length > 0) {{
            md += '### Priority Merges\\n';
            report['merge_recommendations'].slice(0, 5).forEach(rec => {{
                md += `- **${{rec['common_name']}}**: Merge ${{len(rec['files'])}} files (Risk: ${{rec['risk_level']}})\\n`;
            }});
            md += '\\n';
        }}
        
        const dataUri = 'data:text/markdown;charset=utf-8,' + encodeURIComponent(md);
        const link = document.createElement('a');
        link.setAttribute('href', dataUri);
        link.setAttribute('download', 'analysis_report.md');
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        closeModal();
    }}
    
    // Print functionality
    function printDashboard() {{
        window.print();
    }}
    
    // Close modal if clicked outside
    window.onclick = function(event) {{
        const modal = document.getElementById('exportModal');
        if (event.target === modal) {{
            closeModal();
        }}
    }};
    """